config/routes.rb
Referenca::Application.routes.draw do
  get "groups/index"

  resources :authors
  resources :articles do
    member do
      get 'download'
      put 'update_private_fields'
    end
  end
  resources :references
  resources :keywords
  resources :sessions
  resources :users
  resources :groups do
    member do
      post 'invite_to'
    end
  end
  
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'toggle_language' => 'application#toggle_language', :as => :toggle_language
  

  root :to => "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :references, :dependent => :destroy
  has_many :referenced_articles, :through => :references
  accepts_nested_attributes_for :references, :reject_if => lambda {|a| a[:referenced_article_id].blank?}, :allow_destroy => true
  
  has_many :authorships, :dependent => :destroy
  has_many :authors, :through => :authorships
  accepts_nested_attributes_for :authorships, :reject_if => lambda {|a| a[:author_id].blank?}, :allow_destroy => true

  has_many :articles_keywords, :dependent => :destroy
  has_many :keywords, :through => :articles_keywords
  accepts_nested_attributes_for :articles_keywords, :reject_if => lambda {|a| a[:keyword_id].blank?}, :allow_destroy => true

  belongs_to :group
  belongs_to :owner, :class_name => "User"
  
  attr_accessible :title, :authorships_attributes, :references_attributes, :articles_keywords_attributes, :summarize, :journal, :volume, :start_page, :end_page, :paper, :year, :no, :publisher, :edition
  
  mount_uploader :pdf, PdfUploader

  validates :title, :presence => true, :uniqueness => true
  validates :year, :presence => true
  validates :owner, :presence => true
  validates :group, :presence => true

  scope :reference_order, lambda{order("authors.last_name asc").order("year desc").includes(:authors)}
  
  def authors_and_year_for_filename
    authors_and_year_for_long_reference.gsub(/[,\s]/,'_')
  end
  def authors_and_year_for_long_reference
    (authors_for_long_reference+", ").sub(/, /," (#{year}) ").chop.sub(/,$/,'')
  end

  def authors_for_long_reference
    authors.map{|e| "#{e.first_name} #{e.last_name}"}.join(', ')
  end
  
  def authors_for_short_reference
    ret = authorships.map(&:author).map(&:last_name).join(' and ')
    if authors.size == 3
      ret.sub!(" and",",") if authors.size == 3
    elsif authors.size >=3
      ret.sub!(/ and .*/," et al")
    end
    ret
  end
  def authors_straight; authors.map(&:straight_name).join(", ") end

  def edition_for_filename
    edition.present? ? "_#{edition}" : ""
  end

  def extension; pdf.url.split('.').last end
  
  def file?; !no_file? end
  def filename
    "#{publisher_for_filename}#{authors_and_year_for_filename}_-_#{title_for_filename}#{edition_for_filename}.#{extension}"
  end
  
  def first_author
    return "" if authors.empty?
    authors.first.last_name
  end

  def group_assoc(assoc); group end

  def no_empty?; no.nil? || no.empty? end  
  def no_file?; pdf.url.nil? end
  def no_journal?; journal.nil? || journal.blank? end
  
  def owner_assoc(assoc); owner end
  
  def reference; "#{authors_for_short_reference} (#{year}) - #{title}".truncate(60) end

  def pdf_name; pdf.path.split('/').last end

  def private_assoc(assoc); private() end
  
  def publisher_for_filename
    publisher.present? ? "#{publisher}_" : ""
  end

  def self.search(search,sort)
    if search
      if sort.split('", "').size > 1
        sorts = sort[2..-3].split('", "')
        search_string = sorts.map{|e| "authors.#{e} LIKE ?"}.join(' or ')
        where(search_string, *sorts.size.times.map{|e| "%#{search}%"}).includes(:authors)
      elsif sort == "keywords.name"
        where("#{sort} LIKE ?", "%#{search}%").includes(:keywords)
      else
        where("#{sort} LIKE ?", "%#{search}%")
      end
    else
      scoped
    end
  end

  def title_for_filename; title.gsub(/[,\s]/,'_') end
  
  def volume_empty?; volume.nil? || volume.empty? end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include InitArticleForm

  load_and_authorize_resource
  
  def index
    @articles = Article.search(params[:search],params[:sort]).all. #reference_order
      sort_by_author_first_name_then_year.
      public_or_privately_owned(current_user).
      paginate(:per_page=>25,:page => params[:page])
    @sort = params[:sort]
  end

  def show
    @article = Article.find(params[:id])
    @references = @article.references.
      order('no asc').
      public_or_privately_owned_reference(current_user)
    @references_from = Reference.where(:referenced_article_id => @article.id).
      public_or_privately_owned_referenced(current_user)
  end

  def new
    @article = Article.new
    @keyword = Keyword.new
    init_form(3)
  end

  def create
    @article = Article.new(params[:article])
    @article.owner = current_user
    @article.group = Group.where(:title => current_user.username).first
    if @article.save
      flash[:notice] = "Successfully created article."
      redirect_to @article
    else
      init_form
      render :action => 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    @keyword = Keyword.new
    init_rendered_form
  end

  def update
    @article = Article.find(params[:id])
    if !@article.pdf.url.nil? && params[:article][:pdf].blank?
      params[:article][:pdf] = @article.pdf
    end
    if @article.update_attributes(params[:article])
      flash[:notice] = "Successfully updated article."
      redirect_to redirect(params[:back], @article)
    else
      unless @article.errors['authorships.author_id'].empty?
        @article.errors['authorships.author_id'][0] =
          @article.authorships.
          map{|e| e.errors.empty? ? nil : Author.find(e.author_id).straight_name}.
          compact.join(', ') + " has already been taken"
      end
      unless @article.errors['articles_keywords.keyword_id'].empty?
        @article.errors['articles_keywords.keyword_id'][0] =
          @article.articles_keywords.
          map{|e| e.errors.empty? ? nil : Keyword.find(e.keyword_id).name}.
          compact.join(', ') + " has already been taken"
      end
      unless @article.errors['references.referenced_article_id'].empty?
        @article.errors['references.referenced_article_id'][0] =
          @article.references.
          map{|e| e.errors.empty? ? nil : Article.find(e.referenced_article_id).reference}.
          compact.join(', ') + " has already been taken"
      end      
      load_articles
      create_empty_reference if @article.errors["references.referenced_article_id"].empty?
      init_form
      render :action => 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = deleted(:article)
    redirect_to articles_url
  end

  def download
    @article = Article.find(params[:id])
    if @article.pdf.url && File.exist?(path = @article.pdf.url)
      send_file path, :content_type => "application/#{@article.extension}",
      :filename => @article.filename
    else
      redirect_to :back, :alert => "File does not exist."
    end
  end

  def update_private_fields
    @article = Article.find(params[:id])
    @article.private  = params[:article][:private]
    @article.pdf      = params[:article][:pdf]
    @article.group_id = params[:article][:group_id]
    if @article.save
      redirect_to @article
    else
      init_rendered_form
      render :edit
    end
  end

  private
    def redirect(option1,option2)
      return option2 if option1.nil?
      option1.empty? ? option2 : option1
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def attribute(attr,fallback)
    return fallback if attr.nil?
    attr.empty? ? fallback : attr
  end
end

app/views/articles/_article.html.erb
<tr>
  <td id="authors">
    <strong><%= i+1 %>.</strong>
    <%= render "short_reference", :article => article, :ex => nil %>
  <td/>
  <td>
    <% if article.no_file? %>
    <% elsif can? :download, article %>
    <%= link_to(fetch_image(article.pdf.url), download_article_path(article)) %>
    <% end %>
  </td>
  <td><%= link_to t(:show), article if can? :show, article %></td>
  <td><%= link_to t(:edit), edit_article_path(article) if can? :edit, article %></td>
  <td><%= link_to t(:del), article, :confirm => sure?, :method => :delete if can? :destroy, article %></td>
</tr>

app/views/articles/_articles_keyword_fields.html.erb
<li>
  <%= f.label :keyword_id, t(:keyword) %>
  <%= f.select :keyword_id, @keywords, :include_blank => true %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, remove(:keyword) %>
</li>

app/views/articles/_articles_keywords_fields.html.erb
<li>
  <%= f.label :keyword_id, "Keyword" %>
  <%= f.select :keyword_id, @keywords, :include_blank => true %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Keyword" %>
</li>

app/views/articles/_authorship_fields.html.erb
<li>
  <%= f.label :author_id, t(:author) %>
  <%= f.select :author_id, @authors, :include_blank => true %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, remove(:author) %>
</li>

app/views/articles/_form.html.erb
<div class="form">
<%= semantic_form_for @article do |f| %>
  <%= hidden_field_tag :back, params[:back] %>
  <%= f.input :title %>
  <% unless @article.errors['authorships.author_id'].empty? %>
  <li id="article_author_input" class="error">
    <p class="inline-errors"><%= @article.errors['authorships.author_id'].first %></p>
  </li>
  <% end %>
  <%= f.semantic_fields_for :authorships do |ref| %>
    <%= render 'articles/authorship_fields', :f => ref %>
  <% end %>
  <li><%= link_to_add_fields add(:author), f, :authorships %></li>
  <%= f.input :summarize %>
  <li id="article_keyword_input" class="error">
    <p class="inline-errors"><%= @article.errors['articles_keywords.keyword_id'].first %></p>
  </li>
  <%= f.semantic_fields_for :articles_keywords do |ref| %>
    <%= render 'articles/articles_keyword_fields', :f => ref %>
  <% end %>
  <li><%= link_to_add_fields add(:keyword), f, :articles_keywords %></li>
  <%= f.input :journal %>
  <%= f.input :publisher, :input_html => {:class => :number} %>
  <%= f.input :edition, :input_html => {:class => :number} %>
  <%= f.input :year, :input_html => {:class => :number} %>
  <%= f.input :volume, :input_html => {:class => :number} %>
  <%= f.input :no, :label => :issue, :input_html => {:class => :number} %>
  <%= f.input :start_page, :input_html => {:class => :number} %>
  <%= f.input :end_page, :input_html => {:class => :number} %>
  <%= f.input :paper, :label => t(:print) %>
  <div class="clear"></div>
  <li id="article_reference_input" class="error">
    <p class="inline-errors"><%= @article.errors['references.referenced_article_id'].first %></p>
  </li>
  <%= f.semantic_fields_for :references do |ref| %>
    <%= render 'articles/reference_fields', :f => ref %>
  <% end %>
  <% unless @article.new_record? %>
    <li><%= link_to_add_fields add(:reference), f, :references %></li>
  <% end %>
  <%= f.submit button_label, :class => :submit %>
<% end %>
<%= yield :article_links %>
</div>
<br/>

<% if !@article.new_record? && can?(:update_private_fields, @article) %>
<div id="private_fields">
  <a name="private_fields"></a>
  <h1><%= edit(:private_fields) %></h1>
  <div class="form">
    <%= semantic_form_for @article, :url => update_private_fields_article_path(@article), :html => { :method => :put, :multipart => true } do |f| %>
      <%= render "articles/private_fields", :f => f %>
      <%= f.submit update(:private_fields), :class => :submit %>
    <% end %>
  </div>
</div>
<% end %>

<a name="keyword"></a>
<h1><%= new(:keyword) %></h1>
<%= render "keywords/form", :article_page => true, :button_label => create(:keyword) %>
<br />

<a name="author"></a>
<h1><%= new(:author) %></h1>
<%= render "authors/form", :article_page => true, :button_label => create(:author) %>

<script>
<% if !@keyword.errors.empty? %>
  window.location = window.location.href + "#keyword";
<% elsif !@author.errors.empty? %>
  window.location = window.location.href + "#author";
<% elsif !@article.errors[:pdf].empty? %>
  window.location = window.location.href + "#private_fields";
<% end %>
</script>

app/views/articles/_long_reference.html.erb
<% authors = "" %>
<% article.authors.each do |author| %>
  <% if author == ex %>
    <% authors += "<span class=\"exception\">"+author.straight_name+"</span>, " %>
  <% else %>
    <% authors += link_to( author.straight_name, author)+", " %>
  <% end %>
<% end %>
<span id="authors"><%= raw authors.sub(/,/, " (#{article.year})") %></span></span>
<i><%= article.title %></i>.
<%= attribute(article.journal, "JOURNAL")+", " unless article.no_journal? %>
<%= "vol. #{article.volume}, " unless article.volume_empty? %>
<%= "no. #{article.no}, " unless article.no_empty? %>
pp. <%= "#{attribute(article.start_page,
         'START-PAGE')}-#{attribute(article.end_page, 'END-PAGE')}," %>
<%= "(#{article.year})" %>
<% if article.file? && can?(:download, article) %>
  <%= link_to(fetch_image(article.pdf.url), download_article_path(article)) %>
<% end %>
<%= link_to t(:show), article %>
<%= link_to t(:edit), edit_article_path(article, :back => request.fullpath ) if can? :edit, article %>

app/views/articles/_private_fields.html.erb
<%= f.input :private %>
<div class="clear"></div>
<li id="file">
  <% if @article.pdf? %>
  <%= fetch_image(@article.pdf.url) %>
  <%= @article.pdf_name %>
  <% end %>
</li>
<%= f.input :pdf, :as => :file %>
<%= f.input :group, :collection => (Group.where('memberships.user_id' => current_user.id).includes(:memberships).all | [@article.group]).compact, :include_blank => false %>

app/views/articles/_reference_fields.html.erb
<li>
  <%= f.label :referenced_article_id, t(:reference) %>
  <%= f.select :referenced_article_id, @articles, :include_blank => true %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, remove(:reference) %>
</li>
<%= f.input :note, :input_html => { :class => :reference } %>
<%= f.input :no, :label => :number %>

app/views/articles/_short_reference.html.erb
<% authors = "" %>
<% article.authorships.map(&:author).each do |author| %>
  <% if author == ex %>
    <% authors += "<span class=\"exception\">"+author.straight_name+"</span>, " %>
  <% else %>
    <% authors += link_to( author.straight_name, author)+", " %>
  <% end %>
<% end %>
<span id="authors"><%= raw authors.sub(/,/, " (#{article.year})") %></span>
<i><%= article.title %></i>

app/views/articles/edit.html.erb
<% title edit(:article) %>

<% content_for :article_links do %>
  <div id="bottom_links"><%= link_to t(:show), @article %></div>
<% end %>

<%= render 'articles/form', :button_label => update(:article) %>

app/views/articles/index.html.erb
<% title pl(:article) %>
<div class="form">

<%= form_tag articles_path, :method => 'get', :id => "articles_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= select_tag :sort, options_for_select([[t('formtastic.labels.title'),'title'],[t(:author),['first_name','middle_names','last_name']],[t('formtastic.labels.year'),'year'],[t(:keyword),'keywords.name']], @sort) %>
    <%= submit_tag t(:search), :name => nil, :class => :commit %>
  </p>
<% end %>
<br />

<table id="articles">
  <%= render "articles", :articles => @articles %>
</table>
<br />
<%= will_paginate @articles %>

<div id="bottom_links"><%= link_to new(:article), new_article_path if can? :new, Article%></div>
</div>

app/views/articles/index.js.erb
$("table#articles").html("<%= escape_javascript(render("articles",:articles=>@articles)) %>")

app/views/articles/new.html.erb
<% title new(:article) %>

<%= render 'articles/form', :button_label => create(:article) %>

app/views/articles/show.html.erb
<div class="form"><% title @article.title %>
<p id="author">
  <strong><%= t(:author) %>:</strong>
  <% authors = "" %>
  <% @article.authorships.map(&:author).each do |author| %>
    <% authors += link_to(author.straight_name, author)+", " %>
  <% end %>
  <%= raw authors.sub(/, $/,'') %>
</p>
<p>
  <strong><%= t('formtastic.labels.summarize') %>:</strong>
  <%= @article.summarize %>
</p>
<p id="keywords">
  <strong><%= pl(:keyword) %>:</strong>
  <%= raw @article.keywords.map{|e| link_to e.name, e}.join(', ') %>
</p>
<p>
  <strong><%= t('formtastic.labels.journal') %>:</strong>
  <%= @article.journal %>
</p>
<p>
  <strong><%= t('formtastic.labels.volume') %>:</strong>
  <%= @article.volume %>
</p>
<p>
  <strong><%= t('formtastic.labels.issue') %>:</strong>
  <%= @article.no %>
</p>
<p>
  <strong><%= t(:pages) %>:</strong>
  <%= @article.start_page %>-<%= @article.end_page %>
</p>
<p id="file">
  <strong><%= t('formtastic.labels.pdf') %>:</strong>
  <% if @article.no_file? %>
    No
  <% elsif can? :download, @article %>
    <%= link_to(fetch_image(@article.pdf.url), download_article_path(@article)) %>
  <% end %>
</p>
<p>
  <strong><%= t(:print) %>:</strong>
  <%= @article.paper ? "Yes" : "No" %>
</p>

<% unless @references.empty? %>
<br />
<div id="references">
  <strong><%= pl(:reference) %>:</strong>
  <ul>
  <% @references.each do |reference| %>
    <li>
      <% if reference.no  %>
        <strong><%= reference.no %>.</strong>
      <% end %>
      <i><%= "\"#{reference.note}\"" %></i> - 
      <%= render "long_reference", :article => reference.referenced_article, :ex => nil %>
    </li>
  <% end  %>
  </ul>
</div>
<% end %>

<% unless @references_from.empty? %>
<br />
<div id="referenced_from">
  <strong><%= t(:referenced_from) %>:</strong>
  <ul>
  <% @references_from.each do |reference| %>
  <li>
    <% if reference.no %>
      <strong><%= reference.no %>.</strong>
    <% end %>
    <i><%= "\"#{reference.note}\"" %></i> - 
    <%= render "long_reference", :article => reference.article, :ex => nil %>
  </li>
  <% end  %>
  </ul>
</div>
<% end %>

<div id="bottom_links">
  <%= link_to t(:edit), edit_article_path(@article) if can? :edit, @article%>
  <% if can? :delete, @article %>
  | <%= link_to t(:delete), @article, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</div>
</div>