config/routes.rb
Referenca::Application.routes.draw do
  get "groups/index"

  resources :authors
  resources :articles do
    member do
      get 'download'
      put 'update_private_fields'
    end
  end
  resources :references
  resources :keywords
  resources :sessions
  resources :users
  resources :groups do
    member do
      post 'invite_to'
    end
  end
  
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'toggle_language' => 'application#toggle_language', :as => :toggle_language
  

  root :to => "articles#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :first_name, :middle_names, :last_name

  has_many :authorships, :dependent => :destroy
  has_many :articles, :through => :authorships
  
  validates :last_name, :presence => true, :uniqueness => {:scope => [:middle_names, :first_name]}

  def straight_name
    name = first_name
    name += " #{middle_names}" if middle_names?
    name += " #{last_name}"
  end
  
  def reversed_name
    name = "#{last_name}"
    name += ", #{first_name}" unless first_name.blank?
    name += " #{middle_names}" unless middle_names.blank?
    name
  end

#  def to_s; reversed_name end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include InitArticleForm

  load_and_authorize_resource
  
  def index
    @authors = Author.order('last_name asc')
  end

  def show
    @author = Author.includes({:articles => :authors}).find(params[:id])
    @articles = @author.articles.order("year desc").public_or_privately_owned(current_user)
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params[:author])
    id = params[:article_id]
    if @author.save
      flash[:notice] = created(:author)
      redirect_to new_article_path and return if id == "nil"
      redirect_to edit_article_path Article.find(id.to_i) and return unless id.blank?
      redirect_to authors_path
    else
      if id == "nil"
        @article = Article.new
        init_rendered_form(3,:author)
        render 'articles/new'
      elsif !id.blank?
        @article = Article.find(id)
        init_rendered_form(1,:author)
        render 'articles/edit'
      else
        render 'authors/new'
      end
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(params[:author])
      flash[:notice] = "Successfully updated author."
      redirect_to authors_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:notice] = "Successfully destroyed author."
    redirect_to authors_url
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<div class="form">
<%= semantic_form_for @author do |f| %>
  <%= f.input :first_name %>
  <%= f.input :middle_names %>
  <%= f.input :last_name %>
  <%= hidden_field_tag :article_id, @article.new_record? ? "nil" : @article.id if article_page %>
  <%= f.submit button_label, :class => :submit %>
  <%= yield :link %>
<% end %>
</div>

app/views/authors/edit.html.erb
<% title edit(:author) %>

<% content_for :link do %>
<div id="bottom_links">
  <%= link_to t(:show), @author %>
  <%= link_to t(:delete), @author, :confirm => sure?, :method => :delete %>
</div>
<% end %>

<%= render 'form', :article_page => false, :button_label => update(:author) %>

app/views/authors/index.html.erb
<% title pl(:author) %>

<div class="form">
<table>
  <% for author in @authors %>
    <tr>
      <td><%= author.straight_name %></td>
      <td><%= link_to t(:show), author if can? :show, author %></td>
      <td><%= link_to t(:edit), edit_author_path(author) if can? :edit, author %></td>
      <td><%= link_to t(:del), author, :confirm => sure?, :method => :delete if can? :destroy, author %></td>
    </tr>
  <% end %>
</table>
<div id="bottom_links"><%= link_to new(:author), new_author_path if can? :new, Author %></div>
</div>

app/views/authors/new.html.erb
<% title new(:author) %>

<%= render 'form', :article_page => false, :button_label => create(:author) %>

app/views/authors/show.html.erb
<% title @author.straight_name %>

<div class="form">
<% unless @articles.empty? %>
<div id="articles">
  <strong><%= pl(:article) %>:</strong>
  <ol>
  <% @articles.each do |article| %>
  <li>
    <div>
      <%= render "articles/long_reference", :article => article, :ex => @author %>
    </div>
  </li>
  <% end %>
  </ol>
</div>
<% end %>

<div id="bottom_links">
  <%= link_to t(:edit), edit_author_path(@author) if can? :edit, @author %> 
  <% if can? :destroy, @author %>
    | <%= link_to t(:delete), @author, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</div>
</div>