config/routes.rb
Referenca::Application.routes.draw do
  get "groups/index"

  resources :authors
  resources :articles do
    member do
      get 'download'
      put 'update_private_fields'
    end
  end
  resources :references
  resources :keywords
  resources :sessions
  resources :users
  resources :groups do
    member do
      post 'invite_to'
    end
  end
  
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'toggle_language' => 'application#toggle_language', :as => :toggle_language
  

  root :to => "articles#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :articles

  attr_accessible :title
  
  validates :title, :uniqueness => true, :presence => true

  def leaders; usernames(leader_memberships) end
  def members; usernames(member_memberships) end

  private
    def leader_memberships; selected_memberships(:leader) end
    def member_memberships; selected_memberships(:member) end
    def selected_memberships(s); memberships.select{|e| e.role? s} end
    def usernames(mships); mships.map{|e| e.user.username}.join(', ') end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def show
    @membership = Membership.new
  end
  
  def index
    @memberships = Membership.where('user_id' => current_user.id).includes(:group).order('groups.title asc')
  end

  def new
  end

  def create
    if @group.save
      membership = Membership.create!(:roles_mask => 1, :group_id => @group.id)
      current_user.memberships << membership
      redirect_to groups_path, :notice => created(:group)
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to @group, :notice => updated(:group)
    else
      render :edit
    end
  end
  
  def destroy
    @group.destroy
    redirect_to groups_path
  end

  def invite_to
    user = User.where(:username => params[:invite]).first || User.where(:email => params[:invite]).first
    @membership = Membership.new
    if user.nil?
      @membership.errors[:user_id] = "User cannot be found."
      render 'groups/show'
    else
      @membership.group_id = @group.id
      @membership.user_id = user.id
      @membership.roles_mask = 2
      if @membership.save
        redirect_to @group
      else
        @membership.errors[:user_id] = "#{params[:invite]} is already a member."
        render 'groups/show'
      end
    end    
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= semantic_form_for @group do |f| %>
  <%= f.input :title %>
  <%= f.submit button_label, :class => :submit %>
<% end %>

app/views/groups/_group.html.erb
<tr>
  <td><%= group.title %></td>
  <td><%= roles %></td>
  <td><%= link_to t(:show), group %></td>
  <% if can? :edit, group %>
    <td><%= link_to t(:edit), edit_group_path(group) %></td>
  <% end %>
  <% if can? :destroy, group %>
    <td><%= link_to t(:del), group, :confirm => sure?, :method => :delete %></td>  
  <% end %>
</tr>

app/views/groups/edit.html.erb
<% title edit(:group) %>

<div class="form">
  
<%= render 'form', :button_label => update(:group) %>

<div id="bottom_links">
  <%= link_to t(:show), @group %>
  <%= link_to t(:delete), @group, :confirm => sure?, :method => :delete %>
</div>

</div>

app/views/groups/index.html.erb
<% title your_p(:group) %>

<div class="form">
<table id="groups">
<% @memberships.each do |membership| %>
  <%= render membership.group, :roles => membership.roles.map(&:capitalize).join(', ') %>
<% end %>
</table>

<div id="bottom_links">
  <%= link_to new(:group), new_group_path if can? :new, Group %>
</div>

</div>

app/views/groups/new.html.erb
<% title new(:group) %>

<div class="form">
<%= render 'form', :button_label => create(:group) %>
</div>

app/views/groups/show.html.erb
<% title @group.title %>

<div class="form">

<div id="facts">
<p>
  <strong><%= t(:leader) %>:</strong>
  <%= @group.leaders %>
</p>
<p>
  <strong><%= pl(:member) %>:</strong>
  <%= @group.members %>
</p>
</div>

<% if can? :invite_to, @group %>
<div id="invitation">
<%= form_tag invite_to_group_path(@group) do %>
<ul>
  <li id="membership_user_id_input" class="error">
    <p class="inline-errors"><%= @membership.errors[:user_id].last %></p>
  </li>
  <li>
    <%= text_field_tag :invite, params[:invite] %>
    <%= submit_tag t(:invite), :class => :commit %>
  </li>
</ul>
<% end %>
</div>
<% end %>
<div class="clear"></div>

<div id="bottom_links">
  <%= link_to t(:edit), edit_group_path(@group) if can? :edit, @group %> 
  <% if can? :destroy, @group %>
    | <%= link_to t(:delete), @group, :confirm => sure?, :method => :delete %>
  <% end %>
</div>
</div>