config/routes.rb
Referenca::Application.routes.draw do
  get "groups/index"

  resources :authors
  resources :articles do
    member do
      get 'download'
      put 'update_private_fields'
    end
  end
  resources :references
  resources :keywords
  resources :sessions
  resources :users
  resources :groups do
    member do
      post 'invite_to'
    end
  end
  
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  match 'toggle_language' => 'application#toggle_language', :as => :toggle_language
  

  root :to => "articles#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
    <%= stylesheet_link_tag 'print.css', :media => 'print' %>
    <!--[if lt IE 7]>
      <%= stylesheet_link_tag 'ie6.css', :media => 'screen, projection' %>
    <![endif]-->         
    <!--[if lt IE 8]>
      <%= stylesheet_link_tag 'ie.css', :media => 'screen, projection' %>
    <![endif]-->   
    <%= stylesheet_link_tag "application", "form", "default" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <div class="clear"></div>
      <div id="site_nav">
        <%= link_to view(:article), articles_path %>
        | <%= link_to view(:author), authors_path %>
        | <%= link_to view(:keyword), keywords_path %>
        <% if can? :index, Group %>
        | <%= link_to view(:group), groups_path %>
        <% end %>
        | <%= link_to english? ? "日本ご" : "English", toggle_language_path %>
      </div>
      <div id="user_nav">
        <% if current_user %>
        <%= t('message.welcome',:user=>current_user.username) %>
        <%= t('message.not_you?') %>
        <%= link_to t(:log_out), logout_path %>
        <% else %>
        <%= link_to t(:sign_up), signup_path %><%= t(:or) %><%= link_to t(:log_in), login_path %>
        <% end %>
      </div>
      <div class="clear"></div>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>